PRODUCT_VERSION_MAJOR = 20
PRODUCT_VERSION_MINOR = 0

LINEAGE_VERSION_SUFFIX := $(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)$(LINEAGE_EXTRAVERSION)-$(LINEAGE_BUILD)

# Branding 
LINEAGE_VERSION := Optimized-LineageOS-19.1-$(shell date -u +%Y%m%d)-Version$(OPTIMIZED_LINEAGEOS_VERSION)
LINEAGE_DISPLAY_VERSION := $(LINEAGE_VERSION)
TARGET_VENDOR_RELEASE_BUILD_ID := $(LINEAGE_VERSION)
